### PR TITLE
login form mockup

### LINKED ISSUE #2: P-002/design-login-form
As a Pulani stakeholder, i'd like to review the LOGIN form.

**Description:** This task involves designing a wireframe for the login form.

**Acceptance Criteria:** 
- Wireframe (sketch) with these login fields: phone number, password.
- Clearly show entry point to **REGISTER** if one isn't registered yet.

### PR DESCRIPTION
**Pull request by halimahbukirwa**
## Description
A login mock-up form

Fixes #2 
## How Has This Been Tested?
It has been tested basing on the fix provided and the comments posted by my team members

## Screenshots (if applicable, else remove this line / section)
Login test

## Checklist:

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added necessary inline code documentation
- [] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Mwamitovi — CHANGES_REQUESTED** [review]
@halimahbukirwa  despite this being a mockup that we agreed needs to be kept within the project, kindly run `npm test` for our assurance that nothing is broken within the app.

**In fact, that's what the last checkbox within the checklist above required.**  (But you deleted those). Please include those checkboxes, leave them in place and remember to attach a screenshot, and mark the last  box with "x"

**Review by Mwamitovi — CHANGES_REQUESTED** [review]
@halimahbukirwa kindly explain why you deleted this file?
Was it a mistake? Did you notice it? 
Please replace it at the earliest opportunity. 

Thanks

**Review by Nataanthoni — DISMISSED** [review]

**Comment by halimahbukirwa** [comment]
I am so sorry @Mwamitovi , it got deleted by mistake. I am working on replacing it, thank you

**Review by Mwamitovi — APPROVED** [review]
Looks ready for a merge

**Review by Nataanthoni — APPROVED** [review]

**Pull request merged**
